apiVersion: v1
kind: Service
metadata:
  name: nginxserver-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: {{template "app-chart.fullname" . }}-web
  ports:
    - port: 80
      targetPort: 80