apiVersion: v1
kind: Service
metadata:
  name: pythonapp-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: {{template "app-chart.fullname" . }}-python
  ports:
    - port: 5000
      targetPort: 5000